[package]
name = "cosmic-text-editor"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
env_logger = "0.9"
fontdb = "0.9"
lazy_static = "1.4"
log = "0.4"

[dependencies.cosmic-text]
git = "https://github.com/pop-os/cosmic-text"
rev = "e788c175"
features = ["syntect"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
branch = "scale-factor"
default-features = false
features = ["winit_softbuffer"]
#path = "../libcosmic"

[dependencies.rfd]
version = "0.10"
#TODO: iced portal
#default-features = false
#features = ["xdg-portal"]

[features]
default = []
vi = ["cosmic-text/vi"]
