[package]
name = "cosmic-text-editor"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
env_logger = "0.10.0"
fontdb = "0.15.0"
lazy_static = "1.4.0"
log = "0.4.20"
rfd = "0.12.0"

[dependencies.cosmic-text]
git = "https://github.com/pop-os/cosmic-text"
features = ["syntect"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
features = ["wayland"]

[features]
default = []
vi = ["cosmic-text/vi"]
